X.
1	  error: rs576242124 is not in 1000G reference panel.,
2	  traceback: Traceback (most recent call last):\n  File \/analysistools/public_html/apps/LDlink/app/LDlink.py\, line 885, in ldproxy\n    with open('./tmp/proxy' + reference + '.txt', \r\) as fp:\nFileNotFoundError: [Errno 2] No such file or directory: './tmp/proxy0326308076.txt'\n
3	}
